### ISSUE TITLE
Experience with changing Lyric thermostat

### ISSUE THREAD

**Issue by mrose17** [WouterNieuwerth/homeautomation#21]
i'm one of the maintainers of https://github.com/d0n4v4nb3ck3r/homebridge-honeywell-home and am getting some odd errors from the API. the documentation at https://developer.honeywell.com/lyric/apis/post/devices/thermostats/%7BdeviceId%7D doesn't enumerate the possible errors.

during your development have you ever seen something like this:

    POST thermostat: Error: HTTP response 500 Server Error
    payload: {"mode":"Heat","coolSetpoint":73,"heatSetpoint":70,"thermostatSetpointStatus":"TemporaryHold"}
    details: { code: 500, message: 'Script Execution Failed’ }

any help is appreciated!

thanks,

/mtr
cc: @d0n4v4nb3ck3r

**Comment by WouterNieuwerth** [comment]
Hi,

Thanks for reaching out to me!

Although the Honeywell API gave me quite some headaches in the past, I haven't seen this specific error. You're actually getting an error message instead of a response with HTML, which the Honeywell API usually returns when their service is down... Do you also get the Honeywell developer e-mails about server maintainance? Perhaps the Honeywell server was down? I'm afraid I can't be very helpful here.

Wouter.

**Comment by mrose17** [comment]
thanks for replying. I am confident that the error is being relayed as JSON through an HTTP 502 response, and is being returned as JSON text... 

by the way, if you ever find a status page for the honeywell service, or a site other than https://developer.honeywell.com/ that details the honeywell thermostat api, please let me know!
